-- 1. Tabla TORNEO
CREATE TABLE TORNEO (
    id_torneo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    fecha_inicio DATE,
    fecha_fin DATE,
    puntos_victoria NUMBER DEFAULT 3 NOT NULL,
    puntos_empate NUMBER DEFAULT 1 NOT NULL,
    puntos_derrota NUMBER DEFAULT 0 NOT NULL,
    amarillas_para_suspension NUMBER DEFAULT 3 NOT NULL,
    estado VARCHAR2(20) DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

-- 2. Tabla EQUIPO
CREATE TABLE EQUIPO (
    id_equipo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_torneo NUMBER NOT NULL,
    nombre VARCHAR2(100) NOT NULL,
    ciudad VARCHAR2(100),
    tecnico VARCHAR2(100),
    activo CHAR(1) DEFAULT 'S' CHECK (activo IN ('S', 'N')),
    CONSTRAINT fk_equipo_torneo FOREIGN KEY (id_torneo) REFERENCES TORNEO(id_torneo)
);

-- 3. Tabla JUGADOR
CREATE TABLE JUGADOR (
    id_jugador NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_equipo NUMBER NOT NULL,
    nombre VARCHAR2(100) NOT NULL,
    apellido VARCHAR2(100) NOT NULL,
    posicion VARCHAR2(50),
    dorsal NUMBER,
    estado VARCHAR2(20) DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'SUSPENDIDO')),
    activo CHAR(1) DEFAULT 'S' CHECK (activo IN ('S', 'N')),
    CONSTRAINT fk_jugador_equipo FOREIGN KEY (id_equipo) REFERENCES EQUIPO(id_equipo)
);

-- 4. Tabla PARTIDO
CREATE TABLE PARTIDO (
    id_partido NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_torneo NUMBER NOT NULL,
    id_local NUMBER NOT NULL,
    id_visitante NUMBER NOT NULL,
    fecha DATE,
    jornada NUMBER,
    goles_local NUMBER DEFAULT 0,
    goles_visitante NUMBER DEFAULT 0,
    estado VARCHAR2(20) DEFAULT 'PROGRAMADO' CHECK (estado IN ('PROGRAMADO', 'JUGADO', 'SUSPENDIDO')),
    CONSTRAINT fk_partido_torneo FOREIGN KEY (id_torneo) REFERENCES TORNEO(id_torneo),
    CONSTRAINT fk_partido_local FOREIGN KEY (id_local) REFERENCES EQUIPO(id_equipo),
    CONSTRAINT fk_partido_visitante FOREIGN KEY (id_visitante) REFERENCES EQUIPO(id_equipo)
);

-- 5. Tabla POSICION
CREATE TABLE POSICION (
    id_torneo NUMBER NOT NULL,
    id_equipo NUMBER NOT NULL,
    pj NUMBER DEFAULT 0,
    pg NUMBER DEFAULT 0,
    pe NUMBER DEFAULT 0,
    pp NUMBER DEFAULT 0,
    gf NUMBER DEFAULT 0,
    gc NUMBER DEFAULT 0,
    dg NUMBER DEFAULT 0,
    puntos NUMBER DEFAULT 0,
    CONSTRAINT pk_posicion PRIMARY KEY (id_torneo, id_equipo),
    CONSTRAINT fk_posicion_torneo FOREIGN KEY (id_torneo) REFERENCES TORNEO(id_torneo),
    CONSTRAINT fk_posicion_equipo FOREIGN KEY (id_equipo) REFERENCES EQUIPO(id_equipo)
);

-- 6. Tabla TARJETA
CREATE TABLE TARJETA (
    id_tarjeta NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_partido NUMBER NOT NULL,
    id_jugador NUMBER NOT NULL,
    tipo VARCHAR2(20) CHECK (tipo IN ('AMARILLA', 'ROJA')),
    minuto NUMBER,
    CONSTRAINT fk_tarjeta_partido FOREIGN KEY (id_partido) REFERENCES PARTIDO(id_partido),
    CONSTRAINT fk_tarjeta_jugador FOREIGN KEY (id_jugador) REFERENCES JUGADOR(id_jugador)
);

-- 7. Tabla SANCION_JUGADOR
CREATE TABLE SANCION_JUGADOR (
    id_sancion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_jugador NUMBER NOT NULL,
    id_torneo NUMBER NOT NULL,
    motivo VARCHAR2(200),
    partidos_suspendidos NUMBER DEFAULT 1,
    partidos_cumplidos NUMBER DEFAULT 0,
    vigente CHAR(1) DEFAULT 'S' CHECK (vigente IN ('S', 'N')),
    CONSTRAINT fk_sancion_jugador FOREIGN KEY (id_jugador) REFERENCES JUGADOR(id_jugador),
    CONSTRAINT fk_sancion_torneo FOREIGN KEY (id_torneo) REFERENCES TORNEO(id_torneo)
);

-- 8. Tabla AUDITORIA_PARTIDO
CREATE TABLE AUDITORIA_PARTIDO (
    id_auditoria NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_partido NUMBER,
    usuario VARCHAR2(100),
    fecha_hora DATE DEFAULT SYSDATE,
    detalle_antes VARCHAR2(4000),
    detalle_despues VARCHAR2(4000)
);

-- Indices adicionales para rendimiento
CREATE INDEX idx_partido_torneo ON PARTIDO(id_torneo);
CREATE INDEX idx_jugador_equipo ON JUGADOR(id_equipo);



-- 1. Modificar tabla PARTIDO para agregar alineaciones
ALTER TABLE PARTIDO ADD formacion_local VARCHAR2(20);
ALTER TABLE PARTIDO ADD formacion_visitante VARCHAR2(20);

-- 2. Crear tabla GOL
CREATE TABLE GOL (
    id_gol NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_partido NUMBER NOT NULL,
    id_jugador NUMBER NOT NULL,
    minuto NUMBER,
    tipo VARCHAR2(20) DEFAULT 'NORMAL' CHECK (tipo IN ('NORMAL', 'PENAL', 'AUTOGOL')),
    CONSTRAINT fk_gol_partido FOREIGN KEY (id_partido) REFERENCES PARTIDO(id_partido),
    CONSTRAINT fk_gol_jugador FOREIGN KEY (id_jugador) REFERENCES JUGADOR(id_jugador)
);

-- 3. Indices
CREATE INDEX idx_gol_partido ON GOL(id_partido);


------------------------------------------------------------
-- Cateforias/divisiones
------------------------------------------------------------
ALTER TABLE TORNEO ADD categoria VARCHAR2(50) DEFAULT 'LIBRE';
ALTER TABLE TORNEO ADD division VARCHAR2(50);

CREATE TABLE ASCENSO_DESCENSO (
    id_registro NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_torneo_origen NUMBER NOT NULL,
    id_torneo_destino NUMBER NOT NULL,
    id_equipo NUMBER NOT NULL,
    movimiento VARCHAR2(20) CHECK (movimiento IN ('ASCENSO','DESCENSO')),
    CONSTRAINT fk_ad_torneo_origen FOREIGN KEY (id_torneo_origen) REFERENCES TORNEO(id_torneo),
    CONSTRAINT fk_ad_torneo_destino FOREIGN KEY (id_torneo_destino) REFERENCES TORNEO(id_torneo),
    CONSTRAINT fk_ad_equipo FOREIGN KEY (id_equipo) REFERENCES EQUIPO(id_equipo)
);

------------------------------------------------------------
-- Sedes y bloqueos
------------------------------------------------------------
CREATE TABLE SEDE (
    id_sede NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(150) NOT NULL,
    direccion VARCHAR2(200),
    ciudad VARCHAR2(100),
    activo CHAR(1) DEFAULT 'S' CHECK (activo IN ('S','N'))
);

CREATE TABLE SEDE_BLOQUEO (
    id_bloqueo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sede NUMBER NOT NULL,
    fecha_bloqueada DATE NOT NULL,
    motivo VARCHAR2(200),
    CONSTRAINT fk_sede_bloqueo_sede FOREIGN KEY (id_sede) REFERENCES SEDE(id_sede)
);

ALTER TABLE PARTIDO ADD id_sede NUMBER;
ALTER TABLE PARTIDO ADD CONSTRAINT fk_partido_sede FOREIGN KEY (id_sede) REFERENCES SEDE(id_sede);

------------------------------------------------------------
-- Arbitrajes
------------------------------------------------------------
CREATE TABLE ARBITRO (
    id_arbitro NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(150) NOT NULL,
    tipo VARCHAR2(20) DEFAULT 'PRINCIPAL' CHECK (tipo IN ('PRINCIPAL','ASISTENTE','VEEDOR')),
    activo CHAR(1) DEFAULT 'S' CHECK (activo IN ('S','N'))
);

CREATE TABLE PARTIDO_ARBITRAJE (
    id_partido NUMBER NOT NULL,
    id_arbitro NUMBER NOT NULL,
    rol VARCHAR2(20) CHECK (rol IN ('PRINCIPAL','ASISTENTE','VEEDOR')),
    calificacion NUMBER, -- 1-10
    comentarios VARCHAR2(400),
    CONSTRAINT pk_partido_arbitraje PRIMARY KEY (id_partido, id_arbitro, rol),
    CONSTRAINT fk_pa_partido FOREIGN KEY (id_partido) REFERENCES PARTIDO(id_partido),
    CONSTRAINT fk_pa_arbitro FOREIGN KEY (id_arbitro) REFERENCES ARBITRO(id_arbitro)
);

------------------------------------------------------------
-- Reprogramaciones
------------------------------------------------------------
CREATE TABLE PARTIDO_REPROGRAMACION (
    id_reprog NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_partido NUMBER NOT NULL,
    fecha_anterior DATE,
    fecha_nueva DATE NOT NULL,
    motivo VARCHAR2(200),
    notificado CHAR(1) DEFAULT 'N' CHECK (notificado IN ('S','N')),
    CONSTRAINT fk_reprog_partido FOREIGN KEY (id_partido) REFERENCES PARTIDO(id_partido)
);

------------------------------------------------------------
-- Estadisticas
------------------------------------------------------------
CREATE TABLE PARTIDO_EVENTO_JUGADOR (
    id_evento NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_partido NUMBER NOT NULL,
    id_jugador NUMBER NOT NULL,
    minutos_jugados NUMBER,
    asistencias NUMBER DEFAULT 0,
    xg_estimado NUMBER(5,2),
    posicion_en_campo VARCHAR2(20),
    heatmap_json CLOB, -- estructura ligera de posiciones tocadas
    mvp_jornada CHAR(1) DEFAULT 'N' CHECK (mvp_jornada IN ('S','N')),
    CONSTRAINT fk_pej_partido FOREIGN KEY (id_partido) REFERENCES PARTIDO(id_partido),
    CONSTRAINT fk_pej_jugador FOREIGN KEY (id_jugador) REFERENCES JUGADOR(id_jugador)
);

CREATE TABLE RACHA_EQUIPO (
    id_racha NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_equipo NUMBER NOT NULL,
    partidos_invicto NUMBER DEFAULT 0,
    partidos_ganados NUMBER DEFAULT 0,
    goles_favor NUMBER DEFAULT 0,
    goles_contra NUMBER DEFAULT 0,
    desde_fecha DATE,
    hasta_fecha DATE,
    CONSTRAINT fk_racha_equipo FOREIGN KEY (id_equipo) REFERENCES EQUIPO(id_equipo)
);

------------------------------------------------------------
-- Disciplinario ampliado
------------------------------------------------------------
ALTER TABLE SANCION_JUGADOR ADD fecha_inicio DATE;
ALTER TABLE SANCION_JUGADOR ADD fecha_fin DATE;

CREATE TABLE APELACION (
    id_apelacion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sancion NUMBER NOT NULL,
    estado VARCHAR2(20) DEFAULT 'PENDIENTE' CHECK (estado IN ('PENDIENTE','APROBADA','RECHAZADA')),
    motivo VARCHAR2(400),
    respuesta VARCHAR2(400),
    fecha_presentacion DATE DEFAULT SYSDATE,
    fecha_resolucion DATE,
    CONSTRAINT fk_apelacion_sancion FOREIGN KEY (id_sancion) REFERENCES SANCION_JUGADOR(id_sancion)
);


ALTER TABLE TORNEO ADD rojas_para_suspension NUMBER DEFAULT 1;

------------------------------------------------------------
-- Vistas de apoyo
------------------------------------------------------------
CREATE OR REPLACE VIEW V_ARBITROS_POR_PARTIDO AS
SELECT p.id_partido,
       p.fecha,
       pa.id_arbitro,
       a.nombre,
       pa.rol,
       pa.calificacion,
       pa.comentarios
FROM PARTIDO_ARBITRAJE pa
JOIN ARBITRO a ON pa.id_arbitro = a.id_arbitro
JOIN PARTIDO p ON pa.id_partido = p.id_partido;

CREATE OR REPLACE VIEW V_EVENTOS_PARTIDO AS
SELECT e.id_evento,
       e.id_partido,
       e.id_jugador,
       j.nombre || ' ' || j.apellido AS jugador,
       e.minutos_jugados,
       e.asistencias,
       e.xg_estimado,
       e.posicion_en_campo,
       e.mvp_jornada
FROM PARTIDO_EVENTO_JUGADOR e
JOIN JUGADOR j ON e.id_jugador = j.id_jugador;

-- === VISTAS ===
-- 02_views.sql
-- Vistas para TorneoManager

-- 1. Vista de Tabla de Posiciones Ordenada
CREATE OR REPLACE VIEW V_TABLA_POSICIONES AS
SELECT 
    p.id_torneo,
    t.nombre AS nombre_torneo,
    p.id_equipo,
    e.nombre AS nombre_equipo,
    p.pj,
    p.pg,
    p.pe,
    p.pp,
    p.gf,
    p.gc,
    p.dg,
    p.puntos
FROM POSICION p
JOIN EQUIPO e ON p.id_equipo = e.id_equipo
JOIN TORNEO t ON p.id_torneo = t.id_torneo
ORDER BY p.puntos DESC, p.dg DESC, p.gf DESC;



CREATE TABLE PARTIDO_JUGADOR (
    id_partido NUMBER NOT NULL,
    id_jugador NUMBER NOT NULL,
    titular CHAR(1) DEFAULT 'S',
    minutos_jugados NUMBER,
    goles NUMBER DEFAULT 0,
    CONSTRAINT pk_partido_jugador PRIMARY KEY (id_partido, id_jugador),
    CONSTRAINT fk_pj_partido FOREIGN KEY (id_partido) REFERENCES PARTIDO(id_partido),
    CONSTRAINT fk_pj_jugador FOREIGN KEY (id_jugador) REFERENCES JUGADOR(id_jugador)
);

CREATE OR REPLACE VIEW V_GOLEADORES AS
SELECT 
    t.id_torneo,
    j.id_jugador,
    j.nombre || ' ' || j.apellido AS nombre_completo,
    e.nombre AS equipo,
    COUNT(*) AS total_goles
FROM GOL g
JOIN PARTIDO p ON g.id_partido = p.id_partido
JOIN JUGADOR j ON g.id_jugador = j.id_jugador
JOIN EQUIPO e ON j.id_equipo = e.id_equipo
JOIN TORNEO t ON p.id_torneo = t.id_torneo
WHERE p.estado = 'JUGADO'
GROUP BY t.id_torneo, j.id_jugador, j.nombre, j.apellido, e.nombre
HAVING COUNT(*) > 0
ORDER BY total_goles DESC;

-- 3. Vista de Jugadores Sancionados
CREATE OR REPLACE VIEW V_JUGADORES_SANCIONADOS AS
SELECT 
    s.id_sancion,
    s.id_torneo,
    j.nombre || ' ' || j.apellido AS nombre_jugador,
    e.nombre AS equipo,
    s.motivo,
    s.partidos_suspendidos,
    s.partidos_cumplidos,
    (s.partidos_suspendidos - s.partidos_cumplidos) AS partidos_restantes
FROM SANCION_JUGADOR s
JOIN JUGADOR j ON s.id_jugador = j.id_jugador
JOIN EQUIPO e ON j.id_equipo = e.id_equipo
WHERE s.vigente = 'S';

-- 4. Vista Fair Play (Menos tarjetas es mejor)
CREATE OR REPLACE VIEW V_FAIR_PLAY AS
SELECT 
    t.id_torneo,
    e.nombre AS equipo,
    COUNT(CASE WHEN tr.tipo = 'AMARILLA' THEN 1 END) AS amarillas,
    COUNT(CASE WHEN tr.tipo = 'ROJA' THEN 1 END) AS rojas,
    (COUNT(CASE WHEN tr.tipo = 'AMARILLA' THEN 1 END) + 
     COUNT(CASE WHEN tr.tipo = 'ROJA' THEN 1 END) * 3) AS puntos_disciplina
FROM TARJETA tr
JOIN PARTIDO p ON tr.id_partido = p.id_partido
JOIN TORNEO t ON p.id_torneo = t.id_torneo
JOIN JUGADOR j ON tr.id_jugador = j.id_jugador
JOIN EQUIPO e ON j.id_equipo = e.id_equipo
GROUP BY t.id_torneo, e.nombre
ORDER BY puntos_disciplina ASC;

-- === PAQUETES ===

CREATE OR REPLACE PACKAGE PKG_TORNEO AS
    PROCEDURE registrar_resultado(
        p_id_partido IN NUMBER, 
        p_goles_local IN NUMBER, 
        p_goles_visitante IN NUMBER, 
        p_usuario IN VARCHAR2
    );
    PROCEDURE recalcular_tabla(p_id_torneo IN NUMBER);
    PROCEDURE inicializar_posiciones(p_id_torneo IN NUMBER);
END PKG_TORNEO;
/

CREATE OR REPLACE PACKAGE BODY PKG_TORNEO AS

    PROCEDURE inicializar_posiciones(p_id_torneo IN NUMBER) IS
    BEGIN
        -- Insertar registros en POSICION para equipos que no esten
        INSERT INTO POSICION (id_torneo, id_equipo, pj, pg, pe, pp, gf, gc, dg, puntos)
        SELECT p_id_torneo, id_equipo, 0, 0, 0, 0, 0, 0, 0, 0
        FROM EQUIPO
        WHERE id_torneo = p_id_torneo
        AND id_equipo NOT IN (SELECT id_equipo FROM POSICION WHERE id_torneo = p_id_torneo);
    END;

    PROCEDURE recalcular_tabla(p_id_torneo IN NUMBER) IS
        CURSOR c_partidos IS
            SELECT id_local, id_visitante, goles_local, goles_visitante
            FROM PARTIDO
            WHERE id_torneo = p_id_torneo AND estado = 'JUGADO';
            
        v_pts_vic NUMBER;
        v_pts_emp NUMBER;
        v_pts_der NUMBER;
    BEGIN
        -- Obtener reglas del torneo
        SELECT puntos_victoria, puntos_empate, puntos_derrota
        INTO v_pts_vic, v_pts_emp, v_pts_der
        FROM TORNEO WHERE id_torneo = p_id_torneo;

        -- Reiniciar tabla
        UPDATE POSICION SET pj=0, pg=0, pe=0, pp=0, gf=0, gc=0, dg=0, puntos=0
        WHERE id_torneo = p_id_torneo;

        -- Recalcular
        FOR r IN c_partidos LOOP
            -- Local
            UPDATE POSICION SET
                pj = pj + 1,
                gf = gf + r.goles_local,
                gc = gc + r.goles_visitante,
                dg = dg + (r.goles_local - r.goles_visitante),
                pg = pg + CASE WHEN r.goles_local > r.goles_visitante THEN 1 ELSE 0 END,
                pe = pe + CASE WHEN r.goles_local = r.goles_visitante THEN 1 ELSE 0 END,
                pp = pp + CASE WHEN r.goles_local < r.goles_visitante THEN 1 ELSE 0 END,
                puntos = puntos + CASE 
                            WHEN r.goles_local > r.goles_visitante THEN v_pts_vic
                            WHEN r.goles_local = r.goles_visitante THEN v_pts_emp
                            ELSE v_pts_der END
            WHERE id_torneo = p_id_torneo AND id_equipo = r.id_local;

            -- Visitante
            UPDATE POSICION SET
                pj = pj + 1,
                gf = gf + r.goles_visitante,
                gc = gc + r.goles_local,
                dg = dg + (r.goles_visitante - r.goles_local),
                pg = pg + CASE WHEN r.goles_visitante > r.goles_local THEN 1 ELSE 0 END,
                pe = pe + CASE WHEN r.goles_visitante = r.goles_local THEN 1 ELSE 0 END,
                pp = pp + CASE WHEN r.goles_visitante < r.goles_local THEN 1 ELSE 0 END,
                puntos = puntos + CASE 
                            WHEN r.goles_visitante > r.goles_local THEN v_pts_vic
                            WHEN r.goles_visitante = r.goles_local THEN v_pts_emp
                            ELSE v_pts_der END
            WHERE id_torneo = p_id_torneo AND id_equipo = r.id_visitante;
        END LOOP;
    END;

    PROCEDURE registrar_resultado(
        p_id_partido IN NUMBER, 
        p_goles_local IN NUMBER, 
        p_goles_visitante IN NUMBER, 
        p_usuario IN VARCHAR2
    ) IS
        v_id_torneo NUMBER;
        v_estado_ant VARCHAR2(20);
        v_goles_local_ant NUMBER;
        v_goles_visitante_ant NUMBER;
    BEGIN
        SELECT id_torneo, estado, goles_local, goles_visitante 
        INTO v_id_torneo, v_estado_ant, v_goles_local_ant, v_goles_visitante_ant
        FROM PARTIDO WHERE id_partido = p_id_partido;

        -- Actualizar partido
        UPDATE PARTIDO 
        SET goles_local = p_goles_local,
            goles_visitante = p_goles_visitante,
            estado = 'JUGADO'
        WHERE id_partido = p_id_partido;

        -- Auditoria (Simplificada, idealmente en trigger pero aqui tambien vale)
        INSERT INTO AUDITORIA_PARTIDO (id_partido, usuario, detalle_antes, detalle_despues)
        VALUES (p_id_partido, p_usuario, 
                'Estado: ' || v_estado_ant || ', Goles: ' || v_goles_local_ant || '-' || v_goles_visitante_ant,
                'Estado: JUGADO, Goles: ' || p_goles_local || '-' || p_goles_visitante);

        -- Recalcular tabla
        recalcular_tabla(v_id_torneo);
    END;

END PKG_TORNEO;
/

-- ============================================================================
-- PKG_TARJETAS
-- ============================================================================
CREATE OR REPLACE PACKAGE PKG_TARJETAS AS
    PROCEDURE registrar_tarjeta(p_id_partido IN NUMBER, p_id_jugador IN NUMBER, p_tipo IN VARCHAR2, p_minuto IN NUMBER);
    PROCEDURE evaluar_sancion(p_id_jugador IN NUMBER, p_id_torneo IN NUMBER);
END PKG_TARJETAS;
/

CREATE OR REPLACE PACKAGE BODY PKG_TARJETAS AS

    PROCEDURE evaluar_sancion(p_id_jugador IN NUMBER, p_id_torneo IN NUMBER) IS
        v_amarillas NUMBER;
        v_limite_amarillas NUMBER;
        v_tiene_roja NUMBER;
    BEGIN
        -- Obtener limite del torneo
        SELECT amarillas_para_suspension INTO v_limite_amarillas 
        FROM TORNEO WHERE id_torneo = p_id_torneo;


        SELECT COUNT(*) INTO v_amarillas
        FROM TARJETA t
        JOIN PARTIDO p ON t.id_partido = p.id_partido
        WHERE t.id_jugador = p_id_jugador 
          AND p.id_torneo = p_id_torneo 
          AND t.tipo = 'AMARILLA';

  
        IF v_amarillas > 0 AND MOD(v_amarillas, v_limite_amarillas) = 0 THEN
             INSERT INTO SANCION_JUGADOR (id_jugador, id_torneo, motivo, partidos_suspendidos, vigente)
             VALUES (p_id_jugador, p_id_torneo, 'Acumulacion de Amarillas (' || v_amarillas || ')', 1, 'S');
             
             UPDATE JUGADOR SET estado = 'SUSPENDIDO' WHERE id_jugador = p_id_jugador;
        END IF;

    END;

    PROCEDURE registrar_tarjeta(p_id_partido IN NUMBER, p_id_jugador IN NUMBER, p_tipo IN VARCHAR2, p_minuto IN NUMBER) IS
        v_id_torneo NUMBER;
    BEGIN
        INSERT INTO TARJETA (id_partido, id_jugador, tipo, minuto)
        VALUES (p_id_partido, p_id_jugador, p_tipo, p_minuto);

        SELECT id_torneo INTO v_id_torneo FROM PARTIDO WHERE id_partido = p_id_partido;

        IF p_tipo = 'ROJA' THEN
             INSERT INTO SANCION_JUGADOR (id_jugador, id_torneo, motivo, partidos_suspendidos, vigente)
             VALUES (p_id_jugador, v_id_torneo, 'Tarjeta Roja Directa', 1, 'S');
             
             UPDATE JUGADOR SET estado = 'SUSPENDIDO' WHERE id_jugador = p_id_jugador;
        ELSE
             evaluar_sancion(p_id_jugador, v_id_torneo);
        END IF;
    END;

END PKG_TARJETAS;
/

-- === TRIGGERS ===

-- Trigger para asegurar que al crear un equipo se inicialice en la tabla de posiciones si el torneo ya empezo
CREATE OR REPLACE TRIGGER TRG_EQUIPO_INSERT
AFTER INSERT ON EQUIPO
FOR EACH ROW
BEGIN
    INSERT INTO POSICION (id_torneo, id_equipo, pj, pg, pe, pp, gf, gc, dg, puntos)
    VALUES (:NEW.id_torneo, :NEW.id_equipo, 0, 0, 0, 0, 0, 0, 0, 0);
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        NULL; -- Ya existe
END;
/



