-- 01_schema.sql
-- Script de Creación de Tablas y Restricciones para TorneoManager

-- 1. Tabla TORNEO
CREATE TABLE TORNEO (
    id_torneo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    fecha_inicio DATE,
    fecha_fin DATE,
    puntos_victoria NUMBER DEFAULT 3 NOT NULL,
    puntos_empate NUMBER DEFAULT 1 NOT NULL,
    puntos_derrota NUMBER DEFAULT 0 NOT NULL,
    amarillas_para_suspension NUMBER DEFAULT 3 NOT NULL,
    estado VARCHAR2(20) DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

-- 2. Tabla EQUIPO
CREATE TABLE EQUIPO (
    id_equipo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_torneo NUMBER NOT NULL,
    nombre VARCHAR2(100) NOT NULL,
    ciudad VARCHAR2(100),
    tecnico VARCHAR2(100),
    activo CHAR(1) DEFAULT 'S' CHECK (activo IN ('S', 'N')),
    CONSTRAINT fk_equipo_torneo FOREIGN KEY (id_torneo) REFERENCES TORNEO(id_torneo)
);

-- 3. Tabla JUGADOR
CREATE TABLE JUGADOR (
    id_jugador NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_equipo NUMBER NOT NULL,
    nombre VARCHAR2(100) NOT NULL,
    apellido VARCHAR2(100) NOT NULL,
    posicion VARCHAR2(50),
    dorsal NUMBER,
    estado VARCHAR2(20) DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'SUSPENDIDO')),
    activo CHAR(1) DEFAULT 'S' CHECK (activo IN ('S', 'N')),
    CONSTRAINT fk_jugador_equipo FOREIGN KEY (id_equipo) REFERENCES EQUIPO(id_equipo)
);

-- 4. Tabla PARTIDO
CREATE TABLE PARTIDO (
    id_partido NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_torneo NUMBER NOT NULL,
    id_local NUMBER NOT NULL,
    id_visitante NUMBER NOT NULL,
    fecha DATE,
    jornada NUMBER,
    goles_local NUMBER DEFAULT 0,
    goles_visitante NUMBER DEFAULT 0,
    estado VARCHAR2(20) DEFAULT 'PROGRAMADO' CHECK (estado IN ('PROGRAMADO', 'JUGADO', 'SUSPENDIDO')),
    CONSTRAINT fk_partido_torneo FOREIGN KEY (id_torneo) REFERENCES TORNEO(id_torneo),
    CONSTRAINT fk_partido_local FOREIGN KEY (id_local) REFERENCES EQUIPO(id_equipo),
    CONSTRAINT fk_partido_visitante FOREIGN KEY (id_visitante) REFERENCES EQUIPO(id_equipo)
);

-- 5. Tabla POSICION
-- Almacena la tabla de posiciones calculada
CREATE TABLE POSICION (
    id_torneo NUMBER NOT NULL,
    id_equipo NUMBER NOT NULL,
    pj NUMBER DEFAULT 0,
    pg NUMBER DEFAULT 0,
    pe NUMBER DEFAULT 0,
    pp NUMBER DEFAULT 0,
    gf NUMBER DEFAULT 0,
    gc NUMBER DEFAULT 0,
    dg NUMBER DEFAULT 0,
    puntos NUMBER DEFAULT 0,
    CONSTRAINT pk_posicion PRIMARY KEY (id_torneo, id_equipo),
    CONSTRAINT fk_posicion_torneo FOREIGN KEY (id_torneo) REFERENCES TORNEO(id_torneo),
    CONSTRAINT fk_posicion_equipo FOREIGN KEY (id_equipo) REFERENCES EQUIPO(id_equipo)
);

-- 6. Tabla TARJETA
CREATE TABLE TARJETA (
    id_tarjeta NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_partido NUMBER NOT NULL,
    id_jugador NUMBER NOT NULL,
    tipo VARCHAR2(20) CHECK (tipo IN ('AMARILLA', 'ROJA')),
    minuto NUMBER,
    CONSTRAINT fk_tarjeta_partido FOREIGN KEY (id_partido) REFERENCES PARTIDO(id_partido),
    CONSTRAINT fk_tarjeta_jugador FOREIGN KEY (id_jugador) REFERENCES JUGADOR(id_jugador)
);

-- 7. Tabla SANCION_JUGADOR
CREATE TABLE SANCION_JUGADOR (
    id_sancion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_jugador NUMBER NOT NULL,
    id_torneo NUMBER NOT NULL,
    motivo VARCHAR2(200),
    partidos_suspendidos NUMBER DEFAULT 1,
    partidos_cumplidos NUMBER DEFAULT 0,
    vigente CHAR(1) DEFAULT 'S' CHECK (vigente IN ('S', 'N')),
    CONSTRAINT fk_sancion_jugador FOREIGN KEY (id_jugador) REFERENCES JUGADOR(id_jugador),
    CONSTRAINT fk_sancion_torneo FOREIGN KEY (id_torneo) REFERENCES TORNEO(id_torneo)
);

-- 8. Tabla AUDITORIA_PARTIDO
CREATE TABLE AUDITORIA_PARTIDO (
    id_auditoria NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_partido NUMBER,
    usuario VARCHAR2(100),
    fecha_hora DATE DEFAULT SYSDATE,
    detalle_antes VARCHAR2(4000),
    detalle_despues VARCHAR2(4000)
);

-- Indices adicionales para rendimiento
CREATE INDEX idx_partido_torneo ON PARTIDO(id_torneo);
CREATE INDEX idx_jugador_equipo ON JUGADOR(id_equipo);
