-- 05_update_schema.sql
-- Script para agregar funcionalidades de Goles y Alineaciones

-- 1. Modificar tabla PARTIDO para agregar alineaciones
ALTER TABLE PARTIDO ADD formacion_local VARCHAR2(20);
ALTER TABLE PARTIDO ADD formacion_visitante VARCHAR2(20);

-- 2. Crear tabla GOL
CREATE TABLE GOL (
    id_gol NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_partido NUMBER NOT NULL,
    id_jugador NUMBER NOT NULL,
    minuto NUMBER,
    tipo VARCHAR2(20) DEFAULT 'NORMAL' CHECK (tipo IN ('NORMAL', 'PENAL', 'AUTOGOL')),
    CONSTRAINT fk_gol_partido FOREIGN KEY (id_partido) REFERENCES PARTIDO(id_partido),
    CONSTRAINT fk_gol_jugador FOREIGN KEY (id_jugador) REFERENCES JUGADOR(id_jugador)
);

-- 3. Indices
CREATE INDEX idx_gol_partido ON GOL(id_partido);
