-- 07_feature_extensions.sql
-- Extensiones funcionales solicitadas:
-- 1) Calendario avanzado: sedes, bloqueos y reprogramaciones.
-- 2) Arbitrajes: árbitros/veedores y calificación por partido.
-- 3) Estadísticas enriquecidas: MVP, rachas, minutos, asistencias, xG (proxy) y eventos por jugador.
-- 4) Categorías/divisiones y ascensos/descensos.
-- 5) Disciplinario ampliado: apelaciones y cumplimiento de sanciones.

------------------------------------------------------------
-- Categorías / Divisiones
------------------------------------------------------------
ALTER TABLE TORNEO ADD categoria VARCHAR2(50) DEFAULT 'LIBRE';
ALTER TABLE TORNEO ADD division VARCHAR2(50);

CREATE TABLE ASCENSO_DESCENSO (
    id_registro NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_torneo_origen NUMBER NOT NULL,
    id_torneo_destino NUMBER NOT NULL,
    id_equipo NUMBER NOT NULL,
    movimiento VARCHAR2(20) CHECK (movimiento IN ('ASCENSO','DESCENSO')),
    CONSTRAINT fk_ad_torneo_origen FOREIGN KEY (id_torneo_origen) REFERENCES TORNEO(id_torneo),
    CONSTRAINT fk_ad_torneo_destino FOREIGN KEY (id_torneo_destino) REFERENCES TORNEO(id_torneo),
    CONSTRAINT fk_ad_equipo FOREIGN KEY (id_equipo) REFERENCES EQUIPO(id_equipo)
);

------------------------------------------------------------
-- Sedes y bloqueos
------------------------------------------------------------
CREATE TABLE SEDE (
    id_sede NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(150) NOT NULL,
    direccion VARCHAR2(200),
    ciudad VARCHAR2(100),
    activo CHAR(1) DEFAULT 'S' CHECK (activo IN ('S','N'))
);

CREATE TABLE SEDE_BLOQUEO (
    id_bloqueo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sede NUMBER NOT NULL,
    fecha_bloqueada DATE NOT NULL,
    motivo VARCHAR2(200),
    CONSTRAINT fk_sede_bloqueo_sede FOREIGN KEY (id_sede) REFERENCES SEDE(id_sede)
);

ALTER TABLE PARTIDO ADD id_sede NUMBER;
ALTER TABLE PARTIDO ADD CONSTRAINT fk_partido_sede FOREIGN KEY (id_sede) REFERENCES SEDE(id_sede);

------------------------------------------------------------
-- Arbitrajes
------------------------------------------------------------
CREATE TABLE ARBITRO (
    id_arbitro NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(150) NOT NULL,
    tipo VARCHAR2(20) DEFAULT 'PRINCIPAL' CHECK (tipo IN ('PRINCIPAL','ASISTENTE','VEEDOR')),
    activo CHAR(1) DEFAULT 'S' CHECK (activo IN ('S','N'))
);

CREATE TABLE PARTIDO_ARBITRAJE (
    id_partido NUMBER NOT NULL,
    id_arbitro NUMBER NOT NULL,
    rol VARCHAR2(20) CHECK (rol IN ('PRINCIPAL','ASISTENTE','VEEDOR')),
    calificacion NUMBER, -- 1-10
    comentarios VARCHAR2(400),
    CONSTRAINT pk_partido_arbitraje PRIMARY KEY (id_partido, id_arbitro, rol),
    CONSTRAINT fk_pa_partido FOREIGN KEY (id_partido) REFERENCES PARTIDO(id_partido),
    CONSTRAINT fk_pa_arbitro FOREIGN KEY (id_arbitro) REFERENCES ARBITRO(id_arbitro)
);

------------------------------------------------------------
-- Reprogramaciones
------------------------------------------------------------
CREATE TABLE PARTIDO_REPROGRAMACION (
    id_reprog NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_partido NUMBER NOT NULL,
    fecha_anterior DATE,
    fecha_nueva DATE NOT NULL,
    motivo VARCHAR2(200),
    notificado CHAR(1) DEFAULT 'N' CHECK (notificado IN ('S','N')),
    CONSTRAINT fk_reprog_partido FOREIGN KEY (id_partido) REFERENCES PARTIDO(id_partido)
);

------------------------------------------------------------
-- Estadísticas enriquecidas
------------------------------------------------------------
CREATE TABLE PARTIDO_EVENTO_JUGADOR (
    id_evento NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_partido NUMBER NOT NULL,
    id_jugador NUMBER NOT NULL,
    minutos_jugados NUMBER,
    asistencias NUMBER DEFAULT 0,
    xg_estimado NUMBER(5,2),
    posicion_en_campo VARCHAR2(20),
    heatmap_json CLOB, -- estructura ligera de posiciones tocadas
    mvp_jornada CHAR(1) DEFAULT 'N' CHECK (mvp_jornada IN ('S','N')),
    CONSTRAINT fk_pej_partido FOREIGN KEY (id_partido) REFERENCES PARTIDO(id_partido),
    CONSTRAINT fk_pej_jugador FOREIGN KEY (id_jugador) REFERENCES JUGADOR(id_jugador)
);

CREATE TABLE RACHA_EQUIPO (
    id_racha NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_equipo NUMBER NOT NULL,
    partidos_invicto NUMBER DEFAULT 0,
    partidos_ganados NUMBER DEFAULT 0,
    goles_favor NUMBER DEFAULT 0,
    goles_contra NUMBER DEFAULT 0,
    desde_fecha DATE,
    hasta_fecha DATE,
    CONSTRAINT fk_racha_equipo FOREIGN KEY (id_equipo) REFERENCES EQUIPO(id_equipo)
);

------------------------------------------------------------
-- Disciplinario ampliado
------------------------------------------------------------
ALTER TABLE SANCION_JUGADOR ADD fecha_inicio DATE;
ALTER TABLE SANCION_JUGADOR ADD fecha_fin DATE;

CREATE TABLE APELACION (
    id_apelacion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sancion NUMBER NOT NULL,
    estado VARCHAR2(20) DEFAULT 'PENDIENTE' CHECK (estado IN ('PENDIENTE','APROBADA','RECHAZADA')),
    motivo VARCHAR2(400),
    respuesta VARCHAR2(400),
    fecha_presentacion DATE DEFAULT SYSDATE,
    fecha_resolucion DATE,
    CONSTRAINT fk_apelacion_sancion FOREIGN KEY (id_sancion) REFERENCES SANCION_JUGADOR(id_sancion)
);

-- Regla configurable por torneo (amarillas para suspensión ya existe); opcional suspensión automática por rojas
ALTER TABLE TORNEO ADD rojas_para_suspension NUMBER DEFAULT 1;

------------------------------------------------------------
-- Vistas de apoyo
------------------------------------------------------------
CREATE OR REPLACE VIEW V_ARBITROS_POR_PARTIDO AS
SELECT p.id_partido,
       p.fecha,
       pa.id_arbitro,
       a.nombre,
       pa.rol,
       pa.calificacion,
       pa.comentarios
FROM PARTIDO_ARBITRAJE pa
JOIN ARBITRO a ON pa.id_arbitro = a.id_arbitro
JOIN PARTIDO p ON pa.id_partido = p.id_partido;

CREATE OR REPLACE VIEW V_EVENTOS_PARTIDO AS
SELECT e.id_evento,
       e.id_partido,
       e.id_jugador,
       j.nombre || ' ' || j.apellido AS jugador,
       e.minutos_jugados,
       e.asistencias,
       e.xg_estimado,
       e.posicion_en_campo,
       e.mvp_jornada
FROM PARTIDO_EVENTO_JUGADOR e
JOIN JUGADOR j ON e.id_jugador = j.id_jugador;
